image: ruby:3.3

cache:
  paths:
  - _bundle/

before_script:
  - bundle config path _bundle
  - bundle install

build:
  stage: build
  script:
  - bundle exec jekyll b
  - mv _site public
  artifacts:
    paths:
    - public
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll b
  - mv _site public
  artifacts:
    paths:
    - public
  only:
  - master
