image: ruby:2.6

cache:
  paths:
  - _bundle/

before_script:
  - bundle install --path _bundle

build:
  stage: build
  script:
  - bundle exec jekyll b
  artifacts:
    paths:
    - _site
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll s
  artifacts:
    paths:
    - _site
  only:
  - master
